// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package main

// GetResponseParams defines parameters for GetResponse.
type GetResponseParams struct {
	// Status HTTP status code of the response.
	Status *int `form:"status,omitempty" json:"status,omitempty"`
}
