openapi: 3.0.0
info:
  title: Sample Go Server API
  description: API for a Go server with latency and data endpoints.
  version: 1.0.0
servers:
  - url: http://localhost:3434
    description: Development server

paths:
  /:
    get:
      summary: Root Endpoint
      responses:
        '204':
          description: No content

  /latency/{duration}:
    get:
      summary: Get Latency
      parameters:
        - name: duration
          in: path
          required: true
          schema:
            type: string
          description: Duration for latency simulation
      responses:
        '200':
          description: Successful response with latency time
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request if duration is missing or invalid

  /data/{size}:
    get:
      summary: Get Data
      parameters:
        - name: size
          in: path
          required: true
          schema:
            type: string
          description: Size of the data to be returned
      responses:
        '200':
          description: Successful response with data
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request if size is missing or invalid